name: apzah_app
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/group-1336.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-hRV.png
    - assets/page-1/images/subtract.png
    - assets/page-1/images/emailicon.png
    - assets/page-1/images/group-1403.png
    - assets/page-1/images/frame.png
    - assets/page-1/images/frame-8rf.png
    - assets/page-1/images/cover.png
    - assets/page-1/images/frame-aP5.png
    - assets/page-1/images/vector-704.png
    - assets/page-1/images/frame-Uqh.png
    - assets/page-1/images/ellipse-593-bg.png
    - assets/page-1/images/cover-3j1.png
    - assets/page-1/images/auto-group-9js7.png
    - assets/page-1/images/union.png
    - assets/page-1/images/group-1403-Phd.png
    - assets/page-1/images/ellipse-360.png
    - assets/page-1/images/auto-group-udmd.png
    - assets/page-1/images/frame-p6f.png
    - assets/page-1/images/subtract-AAX.png
    - assets/page-1/images/ellipse-587-bg.png
    - assets/page-1/images/ellipse-587-bg-DY7.png
    - assets/page-1/images/cover-5iB.png
    - assets/page-1/images/ellipse-587-bg-Ezw.png
    - assets/page-1/images/ellipse-587-bg-HkF.png
    - assets/page-1/images/ellipse-587-bg-KeK.png
    - assets/page-1/images/emailicon-Ag3.png
    - assets/page-1/images/group-1403-TPZ.png
    - assets/page-1/images/group-1404.png
    - assets/page-1/images/group-1409.png
    - assets/page-1/images/vector-Tym.png
    - assets/page-1/images/vector-705-stroke.png
    - assets/page-1/images/vector-WY3.png
    - assets/page-1/images/frame-gPD.png
    - assets/page-1/images/cover-pwu.png
    - assets/page-1/images/frame-Z1d.png
    - assets/page-1/images/group-1403-U27.png
    - assets/page-1/images/subtract-AFd.png
    - assets/page-1/images/frame-E1q.png
    - assets/page-1/images/auto-group-sjif.png
    - assets/page-1/images/frame-YnP.png
    - assets/page-1/images/auto-group-13fh.png
    - assets/page-1/images/cover-ukf.png
    - assets/page-1/images/auto-group-tgy1.png
    - assets/page-1/images/frame-NQb.png
    - assets/page-1/images/home.png
    - assets/page-1/images/ellipse-367-bg.png
    - assets/page-1/images/frame-RYX.png
    - assets/page-1/images/frame-aSf.png
    - assets/page-1/images/auto-group-awjh.png
    - assets/page-1/images/frame-6Xu.png
    - assets/page-1/images/frame-KSb.png
    - assets/page-1/images/frame-PzB.png
    - assets/page-1/images/auto-group-tpr1.png
    - assets/page-1/images/frame-MR5.png
    - assets/page-1/images/subtract-MtF.png
    - assets/page-1/images/subtract-Bnj.png
    - assets/page-1/images/frame-SyZ.png
    - assets/page-1/images/auto-group-rn4t.png
    - assets/page-1/images/frame-7AK.png
    - assets/page-1/images/subtract-so1.png
    - assets/page-1/images/vector-nkj.png
    - assets/page-1/images/emailicon-Ndh.png
    - assets/page-1/images/auto-group-exqj.png
    - assets/page-1/images/ellipse-592.png
    - assets/page-1/images/ellipse-592-bg.png
    - assets/page-1/images/auto-group-ftyp.png
    - assets/page-1/images/frame-N5Z.png
    - assets/page-1/images/subtract-vcs.png
    - assets/page-1/images/frame-3N3.png
    - assets/page-1/images/learning-bro-1.png
    - assets/page-1/images/cover-WTV.png
    - assets/page-1/images/ellipse-592-bg-XP9.png
    - assets/page-1/images/frame-9Yw.png
    - assets/page-1/images/no-connection-bro-1.png
    - assets/page-1/images/rectangle-2734.png
    - assets/page-1/images/internet-day-bro-1.png
    - assets/page-1/images/rectangle-2721-bg.png
    - assets/page-1/images/cover-17h.png
    - assets/page-1/images/cover-Xxw.png
    - assets/page-1/images/cover-NRR.png
    - assets/page-1/images/auto-group-1iz7.png
    - assets/page-1/images/group-1404-sgw.png
    - assets/page-1/images/subtract-sYP.png
    - assets/page-1/images/cover-RK1.png
    - assets/page-1/images/cover-i3m.png
    - assets/page-1/images/auto-group-unj5.png
    - assets/page-1/images/rectangle-2721-bg-MGo.png
    - assets/page-1/images/vector-JgK.png
    - assets/page-1/images/ellipse-592-bg-W11.png
    - assets/page-1/images/vector-phq.png
    - assets/page-1/images/cover-rWP.png
    - assets/page-1/images/rectangle-2721-bg-j2j.png
    - assets/page-1/images/frame-KH5.png
    - assets/page-1/images/frame-7vK.png
    - assets/page-1/images/rectangle-2735-bg.png
    - assets/page-1/images/frame-TVm.png
    - assets/page-1/images/frame-hFy.png
    - assets/page-1/images/rectangle-2721-bg-PC7.png
    - assets/page-1/images/ellipse-592-bg-RCw.png
    - assets/page-1/images/cover-x35.png
    - assets/page-1/images/frame-V31.png
    - assets/page-1/images/rectangle-2721-bg-SsM.png
    - assets/page-1/images/frame-CWP.png
    - assets/page-1/images/achievement-bro-1.png
    - assets/page-1/images/frame-6dh.png
    - assets/page-1/images/frame-vMq.png
    - assets/page-1/images/subtract-pTD.png
    - assets/page-1/images/frame-Amy.png
    - assets/page-1/images/subtract-EBV.png
    - assets/page-1/images/cover-sQo.png
    - assets/page-1/images/frame-3Xq.png
    - assets/page-1/images/vector-anf.png
    - assets/page-1/images/group-1411.png
    - assets/page-1/images/vector-gd1.png
    - assets/page-1/images/rectangle-2721-bg-CrF.png
    - assets/page-1/images/frame-NEw.png
    - assets/page-1/images/frame-Kfy.png
    - assets/page-1/images/rectangle-2721-bg-5QF.png
    - assets/page-1/images/frame-c8b.png
    - assets/page-1/images/rectangle-2721-bg-JWX.png
    - assets/page-1/images/cover-NJP.png
    - assets/page-1/images/onboarding3.png
    - assets/page-1/images/ellipse-592-3gw.png
    - assets/page-1/images/rectangle-2721-bg-v1H.png
    - assets/page-1/images/group-1411-kTV.png
    - assets/page-1/images/cover-teo.png
    - assets/page-1/images/cover-xCb.png
    - assets/page-1/images/cover-63u.png
    - assets/page-1/images/ellipse-592-bg-t9H.png
    - assets/page-1/images/rectangle-2720.png
    - assets/page-1/images/cover-NaF.png
    - assets/page-1/images/rectangle-2721-bg-jeK.png
    - assets/page-1/images/cover-gZZ.png
    - assets/page-1/images/cover-emH.png
    - assets/page-1/images/rectangle-2721-bg-cTD.png
    - assets/page-1/images/vector-mb1.png
    - assets/page-1/images/usernameicon.png
    - assets/page-1/images/vector-Gi7.png
    - assets/page-1/images/frame-4xj.png
    - assets/page-1/images/frame-T2b.png
    - assets/page-1/images/emailicon-d39.png
    - assets/page-1/images/frame-eXm.png
    - assets/page-1/images/frame-41y.png
    - assets/page-1/images/ellipse-587-bg-vtB.png
    - assets/page-1/images/vector-Wef.png
    - assets/page-1/images/passwordicon.png
    - assets/page-1/images/usernameicon-1Hd.png
    - assets/page-1/images/dateicon.png
    - assets/page-1/images/cover-PLF.png
    - assets/page-1/images/phoneicon.png
    - assets/page-1/images/usernameicon-nmh.png
    - assets/page-1/images/vector-cgj.png
    - assets/page-1/images/vector-WNw.png
    - assets/page-1/images/usernameicon-btF.png
    - assets/page-1/images/scheduling.png
    - assets/page-1/images/cover-KD5.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
